Feature/api
camila-vecindario/challenge_back pull request #2
Opened 2021-03-19 21:04 UTC by camila-vecindario

**Experiment** with API creation:

* Sign up 
* Login
* List users
* get User by Id
* Project creation (price_history assign, project_access creation)
* Project list
* Get project by Id
* Add project member
* Create lead (with and without existing user)

2021-03-20 17:09 UTC, jesus-vecindario commented on app/controllers/auth_controller.rb
> -
No es de esta linea, pero, trata de usar por ejm en este controlador mejor skip_before_action. Asi evitas si agregas otro metodo en el futuro, tener que agregarlo en el before_action except/only

2021-03-20 17:23 UTC, jesus-vecindario commented on app/controllers/project_leads_controller.rb
> +      user.password = DEFAULT_PASS
Si quieres una contraseña generica puedes cambiarlo por ejm por` Devise.friendly_token[0,20]`

2021-03-20 17:58 UTC, jesus-vecindario requested changes

2021-03-20 17:58 UTC, jesus-vecindario commented on app/controllers/project_leads_controller.rb
> +      user.password = DEFAULT_PASS
Si quieres una contraseña generica puedes cambiarlo por ejm por `Devise.friendly_token[0,20]` para que no todos los usuarios queden con la misma contraseña

2021-03-20 17:58 UTC, jesus-vecindario commented on app/controllers/projects_controller.rb
> +    project = Project.find(params[:projectId])
esta linea y la 37 la podrias unificar en un `before_action :set_project` por ejm

2021-03-20 17:58 UTC, jesus-vecindario commented on app/controllers/registrations_controller.rb
>      @user = User.new(user_params)
trata de usar mejor variables locales en lugar de variables de instancia, evita el @ cuando no sea necesario.

2021-03-20 17:58 UTC, jesus-vecindario commented on app/controllers/project_accesses_controller.rb
> +    # members = ProjectAccess.where(project, [params[:projectId]])
Esto lo puedes hacer mejor haciendo un `has_many :allowed_users, through: :project_access, source: :user` en el modelo de proyecto

2021-03-20 17:58 UTC, jesus-vecindario commented on config/routes.rb
>    post '/auth/login', to: 'auth#login'
trata de "encapsular las rutas" dentro de un namespace, por ejm api/ y v1/

2021-03-20 17:58 UTC, jesus-vecindario commented on app/controllers/project_accesses_controller.rb
> +    access.user_id = access_params[:user]
estas lineas te las puedes ahorras con un  ProjectAccess.new(: access_params)

2021-03-20 17:58 UTC, jesus-vecindario commented on app/controllers/project_leads_controller.rb
> +      user.phone = leads_params[:phone]
estas 3 y la 13 y 14, te las ahorras con user = User.new(:leads_params)

2021-03-30 15:05 UTC, jesus-vecindario commented on Gemfile
> +ruby "2.6.6"
🙏

2021-03-30 15:19 UTC, jesus-vecindario requested changes

2021-03-30 15:19 UTC, jesus-vecindario commented on app/controllers/api/v1/projects_controller.rb
> +  skip_before_action  :set_project, only: [:list]
```suggestion
  before_action :set_project, except: [:list]
  skip_before_action  :authorize_req, only: [:list]
```

2021-03-30 15:19 UTC, jesus-vecindario commented on app/controllers/api/v1/projects_controller.rb
> +    @project.attributes = project_params[:project]
Que hace esto?

```suggestion
    @project.update!(project_params[:project])
```

2021-03-30 15:19 UTC, jesus-vecindario commented on app/controllers/api/v1/projects_controller.rb
> +      projects = Project.where("type_project = ?", search_params[:type]).order(:created_at)
puedes usar el projects q ya ordenaste antes
```suggestion
      projects = projects.where("type_project = ?", search_params[:type]).order(:created_at)
```

2021-03-30 15:19 UTC, jesus-vecindario commented on app/controllers/api/v1/registrations_controller.rb
> +    end
Está bien para el ejercicio, pero en la practica esto no seria recomendable, cualquier persona podria enviar el role admin y ponerse como administrador. Solo es como comentario, no tienes q hacer nada ahi jaja

2021-03-30 15:19 UTC, jesus-vecindario commented on app/controllers/api/v1/users_controller.rb
> +  end
podria ser mejor un metodo privado

2021-03-30 16:54 UTC, camila-vecindario commented on app/controllers/api/v1/projects_controller.rb
> +    @project.attributes = project_params[:project]
Por lo que había averiguado actualiza sólo los valores que se han modificado

2021-03-30 16:56 UTC, camila-vecindario commented on app/controllers/api/v1/registrations_controller.rb
> +    end
¿Cómo sería recomendable manejarlo?

2021-04-05 09:39 UTC, merged